# Generated by Django 4.0.3 on 2022-04-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
